name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: check current directory
        run: ls

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run specific test method
        run: ./gradlew test --info
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Copy test results
        run: cp -r build/reports/tests/test/ ./

      - name: Commit and push test results
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Update test results"
          git push -f origin gh-pages