name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-test-methods:
    runs-on: ubuntu-latest
    outputs:
      test-methods: ${{ steps.get-methods.outputs.test-methods }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Get test methods
        id: get-methods
        run: |
          test_methods=$(grep -r '@Test' src/test/java | sed 's/.*src\/test\/java\///;s/\.java:.*@Test//;s/\//./g')
          echo "::set-output name=test-methods::${test_methods}"

  test:
    needs: generate-test-methods
    runs-on: ubuntu-latest
    strategy:
      matrix:
        method: ${{ fromJson(needs.generate-test-methods.outputs.test-methods) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run specific test method
        run: ./gradlew test --info --tests ${{ matrix.method }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/test/

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/test/

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Copy test results
        run: cp -r build/reports/tests/test/ ./

      - name: Commit and push test results
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Update test results"
          git push -f origin gh-pages